name: BuildAndDeployWorkflow

on:
  workflow_dispatch:

  push: 
    branches:
      - master

env:
  IMAGE_NAME: ecofunding-luigi

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{env.IMAGE_NAME}}:latest, ${{ secrets.DOCKER_USER }}/${{env.IMAGE_NAME}}:${{ github.sha }} 

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/ubuntu/ecofunding-luigi
            sudo su
  
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
            docker pull ${{ secrets.DOCKER_USER }}/${{env.IMAGE_NAME}}:latest

            docker compose down
            docker compose up -d

          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY}}
